#!/bin/bash
set -euo pipefail

# --- 1. Configuration ---
DATASET_PATH=$1
GPU_ID=0 
EXP_NAME="zipnerf"

# --- 2. Automated Patch ---
# Ensures distance_mean works without the broadcasting RuntimeError
echo "🔧 Patching Nerfstudio for Zip-NeRF compatibility..."
UTILS_FILE=$(python -c "import nerfstudio.exporter.exporter_utils as e; print(e.__file__)")
sed -i 's/ray_bundle.directions \* depth/ray_bundle.directions * depth.view(-1, 1)/g' "$UTILS_FILE"

# --- 3. Training ---
echo "🚀 Step 1: Training Zip-NeRF (30k Iterations)..."
CUDA_VISIBLE_DEVICES=$GPU_ID ns-train zipnerf \
  --experiment-name "$EXP_NAME" \
  --max-num-iterations 30000 \
  --viewer.quit-on-train-completion True \
  colmap \
  --data "$DATASET_PATH" \
  --colmap-path sparse \
  --train-split-fraction 1.0 \
  --eval-mode all \
  --downscale-factor 1

# Automatically locate the config generated by this run
LATEST_CONFIG=$(ls -t outputs/"$EXP_NAME"/zipnerf/*/config.yml | head -n 1)

# --- 4. Point Cloud Extraction ---
echo "☁️  Step 2: Extracting Refined Point Cloud (1M Points)..."
CUDA_VISIBLE_DEVICES=$GPU_ID ns-export pointcloud \
    --load-config "$LATEST_CONFIG" \
    --output-dir exports/dense_depth_refined_1M/ \
    --num-points 1000000 \
    --remove-outliers True \
    --std-ratio 0.5 \
    --normal-method open3d \
    --use-bounding-box False \
    --save-world-frame True \
    --depth-output-name distance_mean

# --- 5. Rendering ---
echo "🎬 Step 3: Rendering RGB and Raw Depth Dataset..."
CUDA_VISIBLE_DEVICES=$GPU_ID ns-render dataset \
    --load-config "$LATEST_CONFIG" \
    --output-path ./renders/all_outputs \
    --image-format png \
    --rendered-output-names rgb raw-depth \
    --eval-num-rays-per-chunk 49152 \
    --split train

echo "------------------------------------------------"
echo "📂 Export Dir: exports/dense_depth_refined_1M/"
echo "📂 Render Dir: ./renders/all_outputs"
echo "------------------------------------------------"